language: node_js
node_js:
  - "lts/*"
cache: yarn
jobs:
  include:
    - stage: Lint & Test
      script:
        - yarn lint
        - yarn test
before_deploy: yarn build:docs
deploy:
    - provider: pages
      skip_cleanup: true
      github_token: $GH_PAGES_TOKEN
      keep_history: true
      local_dir: docs
      on:
        branch: master
    - provider: script
      script: sh ./scripts/release-js.sh
      on:
        tags: true
        branch: master
